from __future__ import annotations

from config.models import Node5Config
from schemas.enums import SupportDataStatus
from schemas.node4 import Node4Output
from schemas.node5 import RiskDistribution

METHODOLOGY = (
    "Customer risk was synthesized from two independent sources.\n\n"
    "Node 2 provides quantitative survival-risk estimates.\n\n"
    "Node 3 extracts structured qualitative signals from customer support "
    "interactions.\n\n"
    "Node 4 combines these signals using deterministic, versioned rules. Risk "
    "levels and rankings are therefore not generated by the language model.\n\n"
    "Node 5 converts these structured decisions into client-facing language."
)


def build_risk_distribution(output: Node4Output) -> RiskDistribution:
    stats = output.summary_stats
    return RiskDistribution(
        critical=stats.n_critical,
        high=stats.n_high,
        medium=stats.n_medium,
        low=stats.n_low,
        insufficient_data=stats.n_insufficient_data,
    )


def build_executive_summary(output: Node4Output, config: Node5Config) -> str:
    stats = output.summary_stats
    n_ranked = stats.n_critical + stats.n_high + stats.n_medium + stats.n_low
    lines = [
        f"The analysis identified {n_ranked} priority accounts across the current "
        "customer portfolio.",
        "",
        f"{stats.n_critical} accounts were classified as Critical,",
        f"{stats.n_high} as High,",
        f"{stats.n_medium} as Medium,",
        f"{stats.n_low} as Low.",
    ]
    if stats.n_insufficient_data:
        lines.extend(
            [
                "",
                f"{stats.n_insufficient_data} customers had insufficient data for a "
                "reliable assessment.",
            ]
        )
    if stats.n_churned:
        lines.extend(
            [
                "",
                f"{stats.n_churned} customers had already churned and are listed "
                "separately, not ranked.",
            ]
        )
    return "\n".join(lines)


def build_data_quality_notes(output: Node4Output, config: Node5Config) -> list[str]:
    accounts = [*output.ranked_accounts, *output.insufficient_data_accounts]
    n_limited = sum(
        1
        for account in accounts
        if account.qualitative.support_data_status == SupportDataStatus.LIMITED_DATA
    )
    n_insufficient = output.summary_stats.n_insufficient_data
    notes = [
        "The analysis used quantitative survival-model results from Node 2.",
        "The analysis used support interaction signals from Node 3.",
        f"Reference date: {output.reference_date.isoformat()}.",
    ]
    if n_insufficient:
        notes.append(f"{n_insufficient} accounts had insufficient data.")
    if n_limited:
        notes.append(f"{n_limited} accounts had limited support data.")
    n_beyond = sum(
        1 for account in accounts if account.quantitative.forward_status == "beyond_follow_up"
    )
    if n_beyond:
        notes.append(
            f"{n_beyond} accounts have tenure beyond the survival model's observed follow-up; "
            "their quantitative risk is treated as unknown."
        )
    if output.summary_stats.n_churned:
        notes.append(
            f"{output.summary_stats.n_churned} customers had already churned and are "
            "excluded from ranking."
        )
    return notes


def build_methodology() -> str:
    return METHODOLOGY
